#!/usr/bin/env bash
#
# Shared BAML build script for FlameFlare examples.
#
# Assembles a dist/ directory containing:
#   - Worker entry point (index.mjs) bundled with baml_client
#   - @boundaryml/baml package with the correct native addon for the TARGET platform
#
# The target platform defaults to linux-x64-gnu (typical server).
# Override with: TARGET_PLATFORM=darwin-arm64 npm run build
#
# This script expects to be called from a project directory containing:
#   - flameflare.toml (with name, main, compatibility_date, runtime)
#   - src/index.mjs (entry point)
#   - baml_client/ (generated by `npm run generate`)
#   - node_modules/@boundaryml/baml (installed by `npm install`)
#
set -euo pipefail

PROJECT_DIR="$(pwd)"
DIST_DIR="$PROJECT_DIR/dist"

# Target platform for the server (default: linux-x64-gnu)
TARGET_PLATFORM="${TARGET_PLATFORM:-linux-x64-gnu}"

# Read worker name from flameflare.toml
WORKER_NAME=$(grep '^name' "$PROJECT_DIR/flameflare.toml" | head -1 | sed 's/.*= *"\(.*\)"/\1/')
if [ -z "$WORKER_NAME" ]; then
  echo "Error: could not parse name from flameflare.toml" >&2
  exit 1
fi

echo "Building BAML worker '${WORKER_NAME}' for target platform: ${TARGET_PLATFORM}"

# --- Clean ---
rm -rf "$DIST_DIR"
mkdir -p "$DIST_DIR"

# --- Ensure baml_client is generated ---
if [ ! -d "$PROJECT_DIR/baml_client" ]; then
  echo "Error: baml_client/ not found. Run 'npm run generate' first." >&2
  exit 1
fi

# --- Bundle worker + baml_client with esbuild ---
echo "Bundling worker with esbuild..."
npx esbuild "$PROJECT_DIR/src/index.mjs" \
  --bundle \
  --platform=node \
  --format=esm \
  --outfile="$DIST_DIR/index.mjs" \
  --external:@boundaryml/baml \
  --target=node18

# --- Copy @boundaryml/baml package ---
BAML_PKG="$PROJECT_DIR/node_modules/@boundaryml/baml"
if [ ! -d "$BAML_PKG" ]; then
  echo "Error: @boundaryml/baml not found in node_modules. Run 'npm install' first." >&2
  exit 1
fi

mkdir -p "$DIST_DIR/node_modules/@boundaryml"
cp -r "$BAML_PKG" "$DIST_DIR/node_modules/@boundaryml/baml"

# --- Install target platform native addon ---
rm -rf "$DIST_DIR/node_modules/@boundaryml/baml-"*

BAML_VERSION=$(node -e "console.log(require('$DIST_DIR/node_modules/@boundaryml/baml/package.json').version)")
TARGET_PKG="@boundaryml/baml-${TARGET_PLATFORM}@${BAML_VERSION}"
echo "Installing target native addon: ${TARGET_PKG}"

ADDON_TMPDIR=$(mktemp -d)
cd "$ADDON_TMPDIR"
npm install --force --no-save "${TARGET_PKG}" 2>&1 | tail -3 || true

if [ -d "$ADDON_TMPDIR/node_modules/@boundaryml/baml-${TARGET_PLATFORM}" ]; then
  cp -r "$ADDON_TMPDIR/node_modules/@boundaryml/baml-${TARGET_PLATFORM}" \
        "$DIST_DIR/node_modules/@boundaryml/baml-${TARGET_PLATFORM}"
  echo "Installed native addon for ${TARGET_PLATFORM}"
else
  echo ""
  echo "Warning: Could not install ${TARGET_PKG}."
  echo "The BAML WASI fallback may be used at runtime."
  echo ""
fi
rm -rf "$ADDON_TMPDIR"
cd "$PROJECT_DIR"

# --- Generate flameflare.toml for dist/ ---
# Read additional sections from the source flameflare.toml (queues, workflows, vars, etc.)
# and include them in the dist version, but fix the main path.
{
  echo "name = \"${WORKER_NAME}\""
  echo "main = \"index.mjs\""
  echo "compatibility_date = \"2024-01-01\""
  echo "runtime = \"node\""
  echo ""
  # Copy any additional toml sections (queues, workflows, vars) from the source
  awk '
    /^\[/ || /^\[\[/ { in_section=1 }
    /^name[ =]/ && !in_section { next }
    /^main[ =]/ && !in_section { next }
    /^compatibility_date[ =]/ && !in_section { next }
    /^runtime[ =]/ && !in_section { next }
    in_section { print }
  ' "$PROJECT_DIR/flameflare.toml"
} > "$DIST_DIR/flameflare.toml"

echo ""
echo "Build complete! Output in dist/"
echo "  Worker: ${WORKER_NAME}"
echo "  Deploy: cd dist && ff deploy"